"use client";

import { useEffect, useMemo, useState } from "react";
import {
  fetchSynthetic,
  fetchSyntheticCase,
  generateSynthetic,
  syntheticParquetUrl,
  type SyntheticCase,
} from "@/lib/api";
import {
  Card,
  CardHeader,
  ClassChip,
  EmptyState,
  SectionIntro,
  SeverityBadge,
  Skeleton,
  fmtAddress,
  fmtInt,
} from "./ui";
import { SideBySideDiff } from "./solidity";

export default function Synthetic() {
  const [cases, setCases] = useState<SyntheticCase[] | null>(null);
  const [filter, setFilter] = useState<string>("");
  const [search, setSearch] = useState<string>("");
  const [selected, setSelected] = useState<SyntheticCase | null>(null);
  const [loading, setLoading] = useState(false);
  const [genCount, setGenCount] = useState(8);
  const [genStatus, setGenStatus] = useState<string | null>(null);
  const [genBusy, setGenBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function reload() {
    setLoading(true);
    setError(null);
    try {
      const r = await fetchSynthetic({ limit: 1000 });
      setCases(r.results);
      if (!selected && r.results[0]) open(r.results[0]);
    } catch (e) {
      setError(e instanceof Error ? e.message : "load failed");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    reload();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const classes = useMemo(() => {
    if (!cases) return [];
    const s = new Set<string>();
    cases.forEach((c) => s.add(c.vulnerability_class));
    return Array.from(s).sort();
  }, [cases]);

  const filtered = useMemo(() => {
    if (!cases) return [];
    const q = search.trim().toLowerCase();
    return cases.filter((c) => {
      if (filter && c.vulnerability_class !== filter) return false;
      if (!q) return true;
      return (
        (c.title || "").toLowerCase().includes(q) ||
        (c.description || "").toLowerCase().includes(q) ||
        c.case_uid.toLowerCase().includes(q) ||
        (c.anchor_name || "").toLowerCase().includes(q)
      );
    });
  }, [cases, filter, search]);

  async function open(c: SyntheticCase) {
    setSelected(c);
    if (!c.vulnerable_source) {
      try {
        const full = await fetchSyntheticCase(c.case_uid);
        setSelected(full);
      } catch (e) {
        setError(e instanceof Error ? e.message : "case fetch failed");
      }
    }
  }

  async function handleGenerate() {
    setGenBusy(true);
    setGenStatus(null);
    try {
      const r = await generateSynthetic(genCount);
      setGenStatus(`generated/refreshed ${r.rows} rows`);
      await reload();
    } catch (e) {
      setGenStatus(e instanceof Error ? e.message : "generate failed");
    } finally {
      setGenBusy(false);
    }
  }

  return (
    <div className="space-y-4">
      <SectionIntro
        tags={["vulnerable + patched", "anchored"]}
        title="Synthetic cases."
        description="Vulnerable / patched contract pairs generated by a rule-based mutator from real anchor exploits. Each pair carries the exploit precondition and benchmark task — drop into a fine-tune set, an evaluation harness, or use as auditor training material."
      />
      {/* Toolbar */}
      <div className="flex flex-wrap gap-2 items-center">
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="search title, uid, anchor…"
          className="bg-surface-2 border border-border rounded px-3 py-2 text-sm flex-1 min-w-[220px] text-fg-primary placeholder:text-fg-muted focus:border-border-strong outline-none"
        />
        <select
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          className="bg-surface-2 border border-border rounded px-3 py-2 text-sm text-fg-primary focus:border-border-strong outline-none"
        >
          <option value="">all classes</option>
          {classes.map((c) => (
            <option key={c} value={c}>
              {c}
            </option>
          ))}
        </select>

        <div className="ml-auto flex items-center gap-2">
          <input
            type="number"
            min={1}
            max={500}
            value={genCount}
            onChange={(e) => setGenCount(Number(e.target.value))}
            className="bg-surface-2 border border-border rounded px-2 py-2 text-sm w-20 font-mono text-fg-primary focus:border-border-strong outline-none"
          />
          <button
            onClick={handleGenerate}
            disabled={genBusy}
            className="border border-border-strong text-fg-secondary hover:text-fg-primary hover:border-fg-tertiary disabled:opacity-50 px-4 py-2 rounded text-sm font-medium transition-colors"
          >
            {genBusy ? "generating…" : "Generate"}
          </button>
          <a
            href={syntheticParquetUrl()}
            className="bg-fg-primary text-canvas hover:bg-fg-secondary px-4 py-2 rounded text-sm font-medium transition-colors"
          >
            Download Parquet
          </a>
        </div>
      </div>

      {(genStatus || loading) && (
        <div className="text-2xs uppercase tracking-wider text-fg-tertiary">
          {loading && <span className="mr-3">loading…</span>}
          {genStatus}
        </div>
      )}

      {error && (
        <div className="bg-sev-high-bg border border-sev-high/30 text-sev-high px-3 py-2 rounded text-sm">
          {error}
        </div>
      )}

      {/* Two-column layout */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Case list */}
        <Card className="overflow-hidden">
          <CardHeader
            title={
              <>
                Cases{" "}
                <span className="text-fg-tertiary font-mono text-xs ml-1">
                  ({fmtInt(filtered.length)})
                </span>
              </>
            }
            subtitle={cases ? `${classes.length} classes represented` : undefined}
          />
          <ul className="max-h-[680px] overflow-auto py-1">
            {!cases &&
              Array.from({ length: 6 }).map((_, i) => (
                <li key={i} className="px-4 py-3">
                  <Skeleton className="h-4 w-3/4 mb-2" />
                  <Skeleton className="h-3 w-1/2" />
                </li>
              ))}
            {cases && filtered.length === 0 && (
              <li className="px-4 py-8 text-center text-fg-tertiary text-sm">
                No cases match the filter.
              </li>
            )}
            {filtered.map((c) => (
              <li
                key={c.case_uid}
                onClick={() => open(c)}
                className={`px-4 py-3 cursor-pointer transition-colors ${
                  selected?.case_uid === c.case_uid
                    ? "bg-surface-3"
                    : "even:bg-surface-3/70 hover:bg-surface-3/60"
                }`}
              >
                <div className="flex items-start gap-1.5 mb-1.5 flex-wrap">
                  <ClassChip value={c.vulnerability_class} />
                  <SeverityBadge severity={c.severity || "Informational"} />
                </div>
                <div className="text-sm text-fg-primary leading-snug">
                  {c.title || (
                    <span className="text-fg-muted">untitled case</span>
                  )}
                </div>
                <div className="text-2xs uppercase tracking-wider text-fg-tertiary mt-1.5 flex items-center gap-2 font-mono">
                  <span>{c.case_uid.slice(0, 12)}</span>
                  {c.anchor_name && (
                    <>
                      <span className="text-fg-muted">·</span>
                      <span className="text-fg-tertiary normal-case tracking-normal">
                        anchor {c.anchor_name}
                      </span>
                    </>
                  )}
                </div>
              </li>
            ))}
          </ul>
        </Card>

        {/* Detail */}
        <div className="lg:col-span-2 space-y-3">
          {!selected ? (
            <EmptyState
              title="Select a case to inspect."
              description="Each case pairs a vulnerable contract with its patched counterpart and an exploit precondition derived from a real anchor."
            />
          ) : (
            <>
              <Card className="p-5">
                <div className="flex flex-wrap gap-1.5 mb-3">
                  <ClassChip value={selected.vulnerability_class} />
                  <ClassChip value={selected.layer} />
                  <ClassChip value={selected.exploitability} />
                  <SeverityBadge severity={selected.severity || "Informational"} />
                </div>
                <h3 className="text-lg font-medium text-fg-primary leading-tight mb-1.5">
                  {selected.title}
                </h3>
                <p className="text-sm text-fg-secondary leading-relaxed mb-4">
                  {selected.description}
                </p>

                <dl className="grid md:grid-cols-2 gap-x-6 gap-y-3 text-xs border-t border-border pt-4">
                  <div>
                    <dt className="text-2xs uppercase tracking-wider text-fg-tertiary mb-1">
                      Exploit precondition
                    </dt>
                    <dd className="text-fg-secondary leading-relaxed">
                      {selected.exploit_precondition || "—"}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-2xs uppercase tracking-wider text-fg-tertiary mb-1">
                      Benchmark task
                    </dt>
                    <dd className="text-fg-secondary leading-relaxed">
                      {selected.benchmark_task || "—"}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-2xs uppercase tracking-wider text-fg-tertiary mb-1">
                      Anchor
                    </dt>
                    <dd className="text-fg-secondary font-mono">
                      {selected.anchor_name ? (
                        <>
                          {selected.anchor_name}{" "}
                          <span className="text-fg-tertiary">
                            {fmtAddress(selected.anchor_address || undefined)}
                          </span>
                        </>
                      ) : (
                        "—"
                      )}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-2xs uppercase tracking-wider text-fg-tertiary mb-1">
                      Provenance
                    </dt>
                    <dd className="text-fg-secondary font-mono">
                      {selected.provenance}
                      {selected.generator && (
                        <span className="text-fg-tertiary"> · {selected.generator}</span>
                      )}
                    </dd>
                  </div>
                </dl>
              </Card>

              {selected.vulnerable_source && selected.patched_source ? (
                <SideBySideDiff
                  left={selected.vulnerable_source}
                  right={selected.patched_source}
                />
              ) : (
                <div className="border border-dashed border-border rounded-lg p-6 text-center text-fg-tertiary text-sm">
                  Loading source pair…
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
